### ISSUE TITLE
Reopening manually closed problems if SSL error condition is still present

### ISSUE THREAD

**Issue by reinhard-brandstaedter** [360Performance/dynatrace-plugin-certcheck#7]
Currently when a user manually closed an opened problem it is not automatically re-opened if the error condition still exists. This might prevent user-visibility of an issue if the error has been closed.

If a user wants to silence an alert permanently, the proper way should be disabling the check and not just closing a problem.

**Comment by PieterLuttig** [comment]
Hi Reinhard,

Trust you are well.

Are you aware of any issues with the plugin, whereby it's not opening any problems? Since I upgrade to v1.18, the plugin no longer generates error problems for me. 
I have also changed the API token to allow for v2 API access as documented.

Just wondering if you are aware of anyone else who has similar issues?

Regards
Pieter

**Comment by reinhard-brandstaedter** [comment]
Hi @PieterLuttig ,
I'm not aware of such issues. Do you see any suspicious log entries in the plugin log file?
Usually located in /var/lib/dynatrace/remotepluginmodule/log/remoteplugin/custom.remote.python.certcheck ?
Reinhard
